# Name of the display server protocol.
# Find this with the terminal command: `echo $WAYLAND_DISPLAY`
display_name: wayland-0

# Name of the HDMI output port.
# Find this with the terminal command: `wlr-randr` or `xrandr --query`
display_output: HDMI-A-1

# How much to rotate the monitor
rotation: 90

# The path to the background image.
# This image should be the same dimensions as the monitor.
image_path: mona_lisa_1080_1920.jpg
